### ISSUE TITLE
known issues

### ISSUE THREAD

**Issue by NewFuture** [NewFuture/miniprogram-template#4]
* [x] 小程序API定义文件缺少Component wechat-miniprogram/api-typings#21
* [x] htmlhint 插件未更新 Microsoft/vscode-htmlhint#53
* [x] `jsonc`  格式化保留逗号  prettier/prettier#5708
* [x] eslint 插件开启 `no-unnecessary-type-assertion` prettier/prettier-eslint#201
* [ ] `<selfClose/>` tags in `wxml` prettier/prettier#5862
* [ ] ~~stylelint 解析 `wxml` inline `style` 模板变量~~
